### ISSUE TITLE
Build on OSX 10.12.6 with Xcode 9.2 fails

### ISSUE THREAD

**Issue by KaloyanP** [conda-forge/python-feedstock#173]
Hello,

I am trying to debug an issue with [segfaults when using GStreamer through PyGobject in conda](https://gitlab.gnome.org/GNOME/pygobject/issues/183). I have narrowed down the problem to *only* the conda Python binary- it works everywhere else but on Python installed through conda on OSX. Interestingly, the OSX conda build is the only one to use an old XCode compiler (600 ...), so I thought this was the likely culprit. However, when I try to build the main Python recipe, it fails. 

```
clang-4.0: warning: no such sysroot directory: '/opt/MacOSX10.9.sdk' [-Wmissing-sysroot]
```

Hacked away at it by changing the `conda_build_config.yaml` to have `/Library/Developer/CommandLineTools/SDKs/` as the location of the MacOSX sdk, but I still get a failure:

```
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Users/kpashov/anaconda3/conda-bld/python_1522354442033/work/build-static/./python.exe
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /Users/kpashov/anaconda3/conda-bld/python_1522354442033/work/build-static/./python.exe
  Expected in: /usr/lib/libSystem.B.dylib
```

I have found that this is due to some "improvements" of the SDK added by Apple: https://trac.macports.org/ticket/54893

Anyway, how do I compile Python on my machine with a newer compiler? Alternatively, where in conda can I find a version of Python compiled with a slightly newer compiler so I can test?

**Comment by KaloyanP** [comment]
You are right, I was trying to build python from the Anaconda distrubtion. I tried compiling the conda-forge recipe without any changes, but I am still having problems. Should I close this issue, open a new one here, and update it with the following error? Or should I edit this one?

The first error is below, and there are a few more related to the same file, I reckon they are all related.
```
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: can't open input file: /Users/kpashov/anaconda3/conda-bld/python_1522407482328/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/libpython3.6m.dylib for writing (Permission denied)
```

**Comment by jakirkham** [comment]
It looks like you haven't downloaded the appropriate macOS SDK or configured it correctly to use the one you have available. In any event, this seems like a support request, which is better dealt with elsewhere as noted. Going to go ahead and close this out.
